/** Conservative, non-AI parsing of clearly headed syllabus sections. */
export type ParsedAssessment = { title: string; sourceSection: string; sourceExcerpt: string; percentage?: number; points?: number; suggestedType?: "exam-quiz" | "paper-written" | "project" | "presentation-performance" | "discussion-participation" | "lab-practical" | "other"; confidence: "structured" };
export type SyllabusParse = { sections: string[]; outcomes: string[]; assessments: ParsedAssessment[]; description?: string };
const outcomeHeadings = /^(student )?(learning )?outcomes?|course (learning )?outcomes?|course objectives?\s*:?$/i;
const descriptionHeading = /^course description\s*:?$/i;
const assessmentHeading = /^(assignments?|assessments?|course requirements?|graded work|evaluation|grading|exams?|projects?|papers?|major assignments?)\s*:?$/i;
const heading = /^((student )?(learning )?outcomes?|course (learning )?outcomes?|course objectives?|course description|assignments?|assessments?|course requirements?|graded work|evaluation|grading|exams?|projects?|papers?|major assignments?)\s*:?$/i;
const item = /^(?:\d+[.)]|[-•*])\s+(.{3,})$/;
const assessmentTerms = /\b(exams?|quizzes|projects?|papers?|presentations?|reports?|labs?|discussions?|participation|portfolio|assignments?|activities|practicum|performance)\b/i;
const sectionAfter = (lines: string[], start: number) => { const end = lines.findIndex((line, index) => index > start && heading.test(line)); return start < 0 ? [] : lines.slice(start + 1, end === -1 ? undefined : end); };
const typeFor = (title: string): ParsedAssessment["suggestedType"] => /exam|quiz|test/i.test(title) ? "exam-quiz" : /paper|essay|written/i.test(title) ? "paper-written" : /project|portfolio/i.test(title) ? "project" : /presentation|performance|speech/i.test(title) ? "presentation-performance" : /discussion|participation/i.test(title) ? "discussion-participation" : /lab|practic/i.test(title) ? "lab-practical" : assessmentTerms.test(title) ? "other" : undefined;
function candidate(raw: string, section: string): ParsedAssessment | null { const clean = raw.replace(/^(?:\d+[.)]|[-•*])\s*/, "").replace(/\|/g, " ").replace(/\s{2,}/g, " ").trim(); if (!assessmentTerms.test(clean) || clean.length < 3) return null; const percent = clean.match(/(\d{1,3})\s*%/); const points = clean.match(/(\d{1,4})\s*(?:pts?|points)\b/i); const title = clean.replace(/[–—-]?\s*\d{1,3}\s*%/g, "").replace(/[–—-]?\s*\d{1,4}\s*(?:pts?|points)\b/gi, "").trim(); if (!title || /^assignment\s+(?:percent|weight|points?)$/i.test(title)) return null; return { title, sourceSection: section, sourceExcerpt: raw.trim(), percentage: percent ? Number(percent[1]) : undefined, points: points ? Number(points[1]) : undefined, suggestedType: typeFor(title), confidence: "structured" }; }
export function parseSyllabusText(text: string): SyllabusParse { const lines = text.replace(/\r/g, "").split("\n").map((line) => line.trim()).filter(Boolean); const sections = lines.filter((line) => heading.test(line)).map((line) => line.replace(/:$/, "")); const outcomeStart = lines.findIndex((line) => outcomeHeadings.test(line)); const descriptionStart = lines.findIndex((line) => descriptionHeading.test(line)); const outcomes = sectionAfter(lines, outcomeStart).map((line) => line.match(item)?.[1]).filter((line): line is string => Boolean(line)); const assessments: ParsedAssessment[] = []; const seen = new Set<string>(); lines.forEach((line, index) => { if (!assessmentHeading.test(line)) return; const section = line.replace(/:$/, ""); for (const raw of sectionAfter(lines, index)) { const found = candidate(raw, section); const key = found?.title.toLowerCase().replace(/\W/g, ""); if (found && key && !seen.has(key)) { seen.add(key); assessments.push(found); } } }); const descriptionLines = sectionAfter(lines, descriptionStart); return { sections, outcomes, assessments, description: descriptionLines.length ? descriptionLines.join(" ") : undefined }; }
