"use client";

import { useState } from "react";
import { activityById } from "@/src/data/activities";
import { checkActivityPackageQuality } from "@/src/lib/activityPackageQuality";
import { buildActivityPackage } from "@/src/lib/smartDefaults";
import { ACTIVITY_ENHANCEMENTS } from "@/src/data/activityEnhancements";
import { generationQualityFlags } from "@/src/lib/generationQuality";
import type { ActivityPackage, CourseRecord, RecommendationAnswers } from "@/src/types/course";

export default function ActivityPackageStudio({ course, setCourse }: { course: CourseRecord; setCourse: (course: CourseRecord) => void }) {
  const selection = course.activities[0]; const activity = selection ? activityById[selection.activityId] : null;
  const [mode, setMode] = useState<ActivityPackage["mode"]>("quick"); const [topic, setTopic] = useState(course.title);
  const answers: RecommendationAnswers = { goal: { purpose: activity?.purposes[0], actionPrimary: activity?.intellectualActions[0], stage: activity?.learningStages[0] }, context: { format: course.modality, time: activity?.timeOptions[0], classSize: course.enrollment && course.enrollment > 75 ? "large" : course.enrollment && course.enrollment > 30 ? "medium" : "small", grouping: activity?.groupingOptions[0], priorities: [] } };
  const pkg = activity ? buildActivityPackage(activity, answers, { topic, outcome: course.slos[0]?.statement, mode }) : null;
  if (!activity || !selection || !pkg) return <div><div className="section-header"><div className="eyebrow gold">Activity package</div><h2>Quick Build and Guided Build</h2><p>Select an Activity Builder recommendation first. The package will preserve the selected template, visible defaults, and TiLT structure.</p></div><button className="ghost-button" onClick={() => history.back()}>Return to activity finder</button></div>;
  const save = () => setCourse({ ...course, activities: course.activities.map((item) => item.id === selection.id ? { ...item, package: pkg, assumptions: pkg.assumptions } : item), sources: [...course.sources, { id: `source-package-${Date.now()}`, scope: `Activity package: ${activity.name}`, facultyInputs: topic ? [`Topic: ${topic}`] : [], assumptions: pkg.assumptions, template: activity.templateData ? "Activity-specific stored steps" : "Family-level fallback", knowledgeSources: activity.sourceLinks.map((link) => link.label), aiGenerated: false, informationNotUsed: ["No AI model", "No external web pages"] }] });
  const quality = checkActivityPackageQuality(pkg); const flags = generationQualityFlags(activity, pkg, topic); const hasEnhancement = Boolean(ACTIVITY_ENHANCEMENTS[activity.id]);
  return <div><div className="section-header"><div className="eyebrow gold">Activity package</div><h2>Turn a recommendation into a usable plan</h2><p>Quick Build uses visible defaults; Guided Build lets faculty choose the plan mode before editing the saved package. {hasEnhancement ? "This activity includes migrated activity-specific facilitation and criteria." : "This activity uses its stored base template and visible general fallbacks."}</p></div><div className="tool-grid"><button className={`tool-card ${mode === "quick" ? "selected-card" : ""}`} onClick={() => setMode("quick")}><strong>Quick Build</strong><span>Generate a concise TiLT plan from activity metadata and transparent defaults.</span></button><button className={`tool-card ${mode === "guided" ? "selected-card" : ""}`} onClick={() => setMode("guided")}><strong>Guided Build</strong><span>Start with the same deterministic plan, then use it as an editable design review.</span></button></div><label className="field"><span className="field-label">Course topic or material focus</span><input value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="e.g., Nutrient pollution" /></label><div className="tilt-grid">{(["purpose", "task", "criteria"] as const).map((section) => <article className="tilt-card" key={section}><h3>{section === "criteria" ? "Criteria for success" : section[0].toUpperCase() + section.slice(1)}</h3><ol>{pkg.tilt[section].map((line) => <li key={line}>{line}</li>)}</ol></article>)}</div><section className="dashboard-section"><h3>Facilitation plan</h3><ol className="plain-list">{pkg.instructorNotes.slice(0, -2).map((note) => <li key={note}>{note}</li>)}</ol></section><section className="dashboard-section"><h3>Defaults & assumptions</h3><ul className="plain-list">{pkg.assumptions.map((assumption) => <li key={assumption.what}><strong>{assumption.what}</strong> — {assumption.why}</li>)}</ul><p><strong>Grouping:</strong> {pkg.grouping.replaceAll("-", " ")} · <strong>Evaluation:</strong> {pkg.grading} · <strong>Feedback:</strong> {pkg.feedback.replaceAll("-", " ")}</p></section><section className="dashboard-section"><h3>Quality prompts</h3><ul className="plain-list">{quality.map((check) => <li key={check.label}><strong>{check.status === "meets" ? "Complete" : "Review suggested"}:</strong> {check.label}</li>)}</ul></section><section className="dashboard-section"><h3>Generation-quality flags</h3><ul className="plain-list">{flags.map((flag) => <li key={flag.code}><strong>{flag.status === "meets" ? "Ready" : flag.status === "attention" ? "Needs attention" : "Review"}:</strong> {flag.message}</li>)}</ul></section><button className="primary-button" onClick={save}>Save activity package to course</button></div>;
}
