"use client";
import { useMemo, useState } from "react";
import { createTransparentVersion, standardAssignmentReview, tiltFromAssignment } from "@/src/lib/assignmentReview";
import type { Assignment, CourseRecord, TiltSection } from "@/src/types/course";
import FacultyMaterialUpload from "@/src/components/FacultyMaterialUpload";
import PromptHandoffPanel from "@/src/components/PromptHandoffPanel";
const uid = (p: string) => `${p}-${Math.random().toString(36).slice(2, 9)}`;

export default function AssignmentStudio({ course, setCourse, onFindActivity }: { course: CourseRecord; setCourse: (c: CourseRecord) => void; onFindActivity?: () => void }) {
  const [title, setTitle] = useState(""); const [text, setText] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(course.assignments[0]?.id ?? null);
  const add = () => { if (!title.trim()) return; const material = course.materials.filter((m) => m.scope === "assignment" && m.status === "extracted").at(-1); const original = text || material?.extractedText || ""; const assignment: Assignment = { id: uid("assignment"), title: title.trim(), originalText: original, workingText: original, revisedText: "", sourceMaterialId: material?.id, linkedSloIds: [], linkedAssessmentIds: [], linkedActivityIds: [], tilt: tiltFromAssignment(original), reviewStatus: "not-reviewed", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; setCourse({ ...course, assignments: [...course.assignments, assignment] }); setSelectedId(assignment.id); setTitle(""); setText(""); };
  const selected = course.assignments.find((a) => a.id === selectedId);
  const update = (next: Assignment) => setCourse({ ...course, assignments: course.assignments.map((a) => a.id === next.id ? { ...next, updatedAt: new Date().toISOString() } : a) });
  return <div><div className="section-header"><div className="eyebrow gold">Transparent design</div><h2>Review and clarify an assignment</h2><p>Standard Review and TiLT prompts are deterministic guides—not judgments. Your original wording is always retained.</p></div>
    <section className="pathway-panel"><h3>I already have an assignment</h3><FacultyMaterialUpload course={course} setCourse={setCourse} scope="assignment" title="Upload an existing assignment" /><label className="field"><span className="field-label">Or paste assignment text</span><textarea rows={7} value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste faculty-created assignment instructions." /></label><label className="field"><span className="field-label">Assignment title</span><input value={title} onChange={(e) => setTitle(e.target.value)} /></label><button className="secondary-button" onClick={add}>Create assignment from this text</button></section>
    <section className="pathway-panel"><h3>I am designing a new assessment</h3><p>Start with a lightweight draft, then name what students demonstrate, create, and use as evidence.</p><button className="ghost-button" onClick={() => { setTitle("New assessment"); setText("What should students demonstrate?\n\nWhat will students create or do?\n\nWho is the audience, if relevant?\n\nWhat makes successful work?"); }}>Start a compact draft</button></section>
    {course.assignments.length ? <div className="assignment-layout"><aside className="assignment-list" aria-label="Assignments">{course.assignments.map((a) => <button className={a.id === selectedId ? "selected-assignment" : ""} onClick={() => setSelectedId(a.id)} key={a.id}>{a.title}<small>{a.standardReview ? "Standard Review available" : "Not reviewed"}</small></button>)}</aside>{selected && <Editor assignment={selected} course={course} update={update} setCourse={setCourse} onFindActivity={onFindActivity} />}</div> : <section className="empty-state"><h3>No assignments yet</h3><p>Upload, paste, or begin a lightweight draft. You can link outcomes and refine the student-facing version afterward.</p></section>}</div>;
}

function Editor({ assignment, course, update, setCourse, onFindActivity }: { assignment: Assignment; course: CourseRecord; update: (a: Assignment) => void; setCourse: (c: CourseRecord) => void; onFindActivity?: () => void }) {
  const transparent = useMemo(() => createTransparentVersion(assignment), [assignment]); const setTilt = (key: "purpose" | "task" | "criteria", value: string) => update({ ...assignment, tilt: { ...assignment.tilt, [key]: value.split("\n").map((x) => x.trim()).filter(Boolean) } }); const copy = (value: string) => void navigator.clipboard?.writeText(value);
  return <section className="assignment-editor"><div className="entity-card"><div><span className="entity-kicker">Assignment workspace</span><h3>{assignment.title}</h3><p>{assignment.linkedSloIds.length} linked outcome(s) · {assignment.linkedActivityIds?.length ?? 0} linked practice activity(ies)</p></div><button className="primary-button" onClick={() => update({ ...assignment, standardReview: standardAssignmentReview(assignment, course.slos), reviewStatus: "reviewed" })}>Run Standard Review — No AI</button></div>
    <fieldset className="link-picker"><legend>Linked learning outcomes</legend>{course.slos.map((s) => <label key={s.id}><input type="checkbox" checked={assignment.linkedSloIds.includes(s.id)} onChange={() => update({ ...assignment, linkedSloIds: assignment.linkedSloIds.includes(s.id) ? assignment.linkedSloIds.filter((id) => id !== s.id) : [...assignment.linkedSloIds, s.id] })} /> {s.statement}</label>)}</fieldset>
    <fieldset className="link-picker"><legend>Preparatory learning activities</legend>{course.activities.length ? course.activities.map((activity) => <label key={activity.id}><input type="checkbox" checked={assignment.linkedActivityIds?.includes(activity.id) ?? false} onChange={() => { const current = assignment.linkedActivityIds ?? []; update({ ...assignment, linkedActivityIds: current.includes(activity.id) ? current.filter((id) => id !== activity.id) : [...current, activity.id] }); }} /> {activity.activityName}</label>) : <p className="status-text">No learning activities are saved yet. Use Find a learning activity, then return here to link it.</p>}</fieldset>
    <label className="field"><span className="field-label">Working version</span><small>Edit freely. The original remains available below.</small><textarea rows={12} value={assignment.workingText ?? assignment.originalText} onChange={(e) => update({ ...assignment, workingText: e.target.value })} /></label><details><summary>Original assignment (preserved)</summary><pre className="ai-response">{assignment.originalText || "No original text was provided."}</pre></details>
    <section className="review-panel"><h3>Standard Review — No AI</h3>{assignment.standardReview ? <ul className="plain-list">{assignment.standardReview.findings.map((f, i) => <li key={i}><strong>{f.area} · {f.status.replaceAll("-", " ")}:</strong> {f.detail}</li>)}</ul> : <p className="status-text">Run the deterministic review to inspect visible structure, links, and clarity signals.</p>}<p className="status-text">AI-Assisted Review can later consider discipline and less-explicit directions. It is currently disabled.</p></section>
    <section className="tilt-grid"><Tilt title="Purpose" value={assignment.tilt.purpose} help="Why the work matters and what students practice." change={(v) => setTilt("purpose", v)} /><Tilt title="Task" value={assignment.tilt.task} help="What students will do, create, and submit." change={(v) => setTilt("task", v)} /><Tilt title="Criteria for Success" value={assignment.tilt.criteria} help="What successful work looks like." change={(v) => setTilt("criteria", v)} /></section>
    {!assignment.linkedActivityIds?.length && <div className="gap-card"><span>This assignment currently has no linked practice activity.</span><button className="secondary-button small-button" onClick={onFindActivity}>Find a learning activity</button></div>}
    <section className="review-panel"><h3>Student-facing transparent version</h3><p>Assembled from faculty text and confirmed TiLT fields. Missing information is shown as a question, never invented.</p><pre className="ai-response">{transparent}</pre><div className="button-row"><button className="secondary-button" onClick={() => { update({ ...assignment, revisedText: transparent }); copy(transparent); }}>Copy student-facing assignment</button><button className="ghost-button" onClick={() => copy(assignment.workingText ?? assignment.originalText)}>Copy faculty version</button><button className="ghost-button" onClick={() => window.print()}>Print-friendly view</button></div></section>
    <PromptHandoffPanel course={course} setCourse={setCourse} task="transparent-design" assignment={assignment} />
  </section>;
}
function Tilt({ title, value, help, change }: { title: string; value: string[]; help: string; change: (v: string) => void }) { return <article className="tilt-card"><h3>{title}</h3><p className="status-text">{help}</p><textarea aria-label={`${title} statements, one per line`} rows={6} value={value.join("\n")} onChange={(e) => change(e.target.value)} placeholder="Add faculty-confirmed information, one item per line." /></article>; }
