"use client";

import { useState } from "react";
import { courseReviewCategories, type ReviewRoute } from "@/src/data/courseReviewLibrary";
import { reviewEvidence } from "@/src/lib/courseReview";
import type { CourseRecord, CourseReviewReflection, CourseReviewResponse } from "@/src/types/course";

const responses: Array<{ id: CourseReviewResponse; label: string }> = [{ id: "looks-good", label: "Looks good" }, { id: "revisit", label: "I’d like to revisit this" }, { id: "unsure", label: "I’m not sure" }, { id: "not-applicable", label: "Not applicable" }];

export default function CourseReview({ course, setCourse, onNavigate }: { course: CourseRecord; setCourse: (course: CourseRecord) => void; onNavigate: (route: ReviewRoute) => void }) {
  const [open, setOpen] = useState<string | null>(null); const saved = course.courseReviewReflections ?? [];
  const latest = (criterionId: string) => [...saved].reverse().find((reflection) => reflection.criterionId === criterionId);
  const save = (categoryId: string, criterionId: string, response: CourseReviewResponse, actionId?: string) => setCourse({ ...course, courseReviewReflections: [...saved, { id: `course-review-${Date.now()}-${criterionId}`, categoryId, criterionId, response, actionId, createdAt: new Date().toISOString(), source: "course-self-review-codepen" }] });
  const priority = courseReviewCategories.filter((category) => category.phaseOne); const broader = courseReviewCategories.filter((category) => !category.phaseOne);
  return <div><div className="section-header"><div className="eyebrow gold">Course review</div><h2>A broader look at the student experience</h2><p>Course Review helps you choose where to focus. It distinguishes what this course record can show from what only you can judge.</p></div><section className="next-step"><div><div className="eyebrow gold">Areas you want to revisit</div><h3>{saved.filter((reflection) => reflection.response === "revisit").length} saved focus area{saved.filter((reflection) => reflection.response === "revisit").length === 1 ? "" : "s"}</h3><p>These are prompts for design work—not a course score or compliance result.</p></div><button className="primary-button" onClick={() => onNavigate("dashboard")}>Open workspace</button></section><div className="review-category-grid">{priority.map((category) => <Category key={category.id} category={category} course={course} latest={latest} open={open} setOpen={setOpen} save={save} onNavigate={onNavigate} />)}</div><details className="broader-review"><summary>Broader course experience</summary><p>Syllabus, Navigation, Student Support, Academic Honesty, Course Materials, Teacher Presence/RSI, and Accessibility require your knowledge of the live course—not a false claim from a syllabus.</p><div className="review-category-grid">{broader.map((category) => <Category key={category.id} category={category} course={course} latest={latest} open={open} setOpen={setOpen} save={save} onNavigate={onNavigate} />)}</div></details></div>;
}

function Category({ category, course, latest, open, setOpen, save, onNavigate }: { category: typeof courseReviewCategories[number]; course: CourseRecord; latest: (id: string) => CourseReviewReflection | undefined; open: string | null; setOpen: (id: string | null) => void; save: (categoryId: string, criterionId: string, response: CourseReviewResponse, actionId?: string) => void; onNavigate: (route: ReviewRoute) => void }) { return <section className="review-category"><div><div className="eyebrow gold">{category.phaseOne ? "Design focus" : "Faculty reflection"}</div><h3>{category.title}</h3><p>{category.description}</p></div>{category.criteria.map((criterion) => { const current = latest(criterion.id); const expanded = open === criterion.id; return <article className="review-criterion" key={criterion.id}><h4>{criterion.title}</h4><div className="review-evidence"><strong>{criterion.evidenceType === "document-supported" ? "What we can see" : criterion.evidenceType === "course-shell-review" ? "Course/LMS evidence needed" : "What we can see—and what you can judge"}</strong><p>{reviewEvidence(course, criterion)}</p></div><div className="review-response" role="group" aria-label={`Your reflection: ${criterion.title}`}>{responses.map((response) => <button key={response.id} className={current?.response === response.id ? "selected-button small-button" : "ghost-button small-button"} onClick={() => { save(category.id, criterion.id, response.id); setOpen(response.id === "unsure" ? criterion.id : null); }}>{response.label}</button>)}</div>{current?.response === "revisit" && criterion.actions && <div className="button-row review-actions">{criterion.actions.map((action) => <button key={action.id} className="secondary-button small-button" onClick={() => { save(category.id, criterion.id, "revisit", action.id); onNavigate(action.route); }}>{action.label}</button>)}</div>}{(expanded || current?.response === "unsure") && <details open className="review-questions"><summary>Questions to consider</summary><p>{criterion.guidance}</p><ul>{criterion.questions.map((question) => <li key={question}>{question}</li>)}</ul></details>}<small>Framework source: {category.source}</small></article>; })}</section>; }
