"use client";

import { useRef, useState } from "react";
import type { CourseRecord, FacultyMaterial } from "@/src/types/course";

export default function FacultyMaterialUpload({ course, setCourse, scope, title }: { course: CourseRecord; setCourse: (course: CourseRecord) => void; scope: FacultyMaterial["scope"]; title?: string }) {
  const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(""); const materials = course.materials.filter((material) => material.scope === scope);
  const upload = async (file?: File) => { if (!file) return; setMessage("Extracting readable text locally on the prototype server…"); const form = new FormData(); form.append("file", file); try { const response = await fetch("/api/materials/extract", { method: "POST", body: form }); const data = await response.json() as { material?: Omit<FacultyMaterial, "id" | "scope" | "uploadedAt">; error?: string }; if (!data.material) { setMessage(data.error ?? "Extraction could not be completed."); return; } const material: FacultyMaterial = { ...data.material, id: `material-${Date.now()}`, scope, uploadedAt: new Date().toISOString() }; setCourse({ ...course, materials: [...course.materials.filter((item) => item.scope !== scope), material] }); setMessage(material.message); } catch { setMessage("Extraction could not be completed. The file was not retained."); } };
  return <section className="material-panel"><h3>{title ?? (scope === "course" ? "Course or syllabus material" : "Assignment material")}</h3><p className="status-text">Upload .docx, .pdf, .txt, or .md. The prototype saves extracted text and source metadata in this course record; it does not retain the original file or send it to OpenAI.</p><input ref={input} className="sr-only" type="file" accept=".docx,.pdf,.txt,.md,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,text/markdown" onChange={(event) => { void upload(event.target.files?.[0]); event.target.value = ""; }} /><button className="ghost-button" onClick={() => input.current?.click()}>Upload file</button>{message && <p className="status-text" aria-live="polite">{message}</p>}{materials.map((material) => <article className="material-card" key={material.id}><strong>{material.filename}</strong><span>{material.status === "extracted" ? `${material.characterCount.toLocaleString()} characters extracted` : "Extraction failed"}</span><p>{material.message}</p>{material.extractedText && <details><summary>Review and edit extracted text</summary><textarea aria-label={`Extracted text from ${material.filename}`} rows={12} value={material.extractedText} onChange={(event) => setCourse({ ...course, materials: course.materials.map((item) => item.id === material.id ? { ...item, extractedText: event.target.value, characterCount: event.target.value.length } : item) })} /></details>}<button className="ghost-button small-button" onClick={() => setCourse({ ...course, materials: course.materials.filter((item) => item.id !== material.id) })}>Remove material</button></article>)}</section>;
}
