"use client";

import { useState } from "react";
import type { AIUseDecision, CourseRecord } from "@/src/types/course";

const uid = () => `ai-decision-${Math.random().toString(36).slice(2, 9)}`;
const descriptions = { resist: "Restrict AI because performing the cognitive work itself is part of the learning objective.", reveal: "Allow AI use while requiring students to disclose AI contributions and make their thinking/process visible.", remix: "Redesign the task so AI supports critique, judgment, synthesis, or authentic disciplinary work." };

export default function IntentionalAiStudio({ course, setCourse }: { course: CourseRecord; setCourse: (course: CourseRecord) => void }) {
  const [framework, setFramework] = useState<AIUseDecision["framework"]>("reveal"); const [rationale, setRationale] = useState(""); const [statement, setStatement] = useState("");
  const save = () => { const decision: AIUseDecision = { id: uid(), scope: "course", framework, rationale: rationale.trim(), studentFacingStatement: statement.trim() || defaultStatement(framework) }; setCourse({ ...course, aiDecisions: [...course.aiDecisions, decision], sources: [...course.sources, { id: `source-${decision.id}`, scope: "Course AI approach", facultyInputs: rationale.trim() ? ["Faculty rationale"] : [], assumptions: [], template: "Resist / Reveal / Remix framework", knowledgeSources: ["Summary of Teaching with AI (required knowledge source when configured)"], aiGenerated: false, informationNotUsed: ["No AI model was used to make this decision"] }] }); setRationale(""); setStatement(""); };
  return <div><div className="section-header"><div className="eyebrow gold">Intentional AI use</div><h2>Make an explicit course-level AI decision</h2><p>Choose an approach, explain the judgment, and save an editable student-facing statement. This deterministic decision aid does not claim to be institutional policy.</p></div><div className="tool-grid">{(Object.keys(descriptions) as AIUseDecision["framework"][]).map((choice) => <button key={choice} className={`tool-card ${framework === choice ? "selected-card" : ""}`} onClick={() => setFramework(choice)}><strong>{choice[0].toUpperCase() + choice.slice(1)}</strong><span>{descriptions[choice]}</span></button>)}</div><label className="field"><span className="field-label">Faculty rationale</span><textarea rows={3} value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder="What cognitive labor should students perform, and why?" /></label><label className="field"><span className="field-label">Student-facing statement (editable)</span><textarea rows={3} value={statement} onChange={(event) => setStatement(event.target.value)} placeholder={defaultStatement(framework)} /></label><button className="primary-button" onClick={save}>Save AI approach</button>{course.aiDecisions.length > 0 && <ul className="plain-list">{course.aiDecisions.map((decision) => <li key={decision.id}><strong>{decision.framework.toUpperCase()}:</strong> {decision.studentFacingStatement}</li>)}</ul>}</div>;
}

function defaultStatement(framework: AIUseDecision["framework"]) { return framework === "resist" ? "Do not use generative AI for this work because practicing the underlying thinking is a course learning objective." : framework === "reveal" ? "You may use generative AI only when you disclose the tool, prompts, contribution, and how your own judgment shaped the submitted work." : "Use generative AI as a material for critique or comparison, then make and defend your own disciplinary judgment."; }
