"use client";
import { useState } from "react";
import { buildPromptHandoff, type HandoffTask } from "@/src/lib/promptHandoff";
import type { Assignment, CourseRecord } from "@/src/types/course";
const uid = () => `external-ai-${Math.random().toString(36).slice(2, 9)}`;
export default function PromptHandoffPanel({ course, setCourse, task, assignment }: { course: CourseRecord; setCourse: (c: CourseRecord) => void; task: HandoffTask; assignment?: Assignment }) {
  const handoff = buildPromptHandoff(course, task, assignment); const [prompt, setPrompt] = useState(handoff.prompt); const [feedback, setFeedback] = useState(""); const [provider, setProvider] = useState("");
  return <details className="handoff-panel"><summary>Continue with an AI Assistant</summary><p>Course Guide prepares this prompt locally; it does not send it anywhere. Copy it into an AI assistant available to you through your institution or personal account. Follow institutional guidance and do not include identifiable student information. External services have their own privacy policies.</p><p className="status-text"><strong>This prompt uses:</strong> {handoff.sources.join(" · ") || "faculty-entered context"}</p>{handoff.attachDocument && <p className="status-text">Attach the source syllabus or assignment to your chosen AI assistant if it needs more detail.</p>}<label className="field"><span className="field-label">Editable prompt</span><textarea rows={12} value={prompt} onChange={(e) => setPrompt(e.target.value)} /></label><button className="secondary-button" onClick={() => void navigator.clipboard?.writeText(prompt)}>Copy prompt</button><details><summary>Save AI feedback (optional)</summary><label className="field"><span className="field-label">Provider (optional)</span><input value={provider} onChange={(e) => setProvider(e.target.value)} /></label><label className="field"><span className="field-label">Paste feedback for your reference</span><textarea rows={6} value={feedback} onChange={(e) => setFeedback(e.target.value)} /></label><button className="ghost-button" onClick={() => { if (!feedback.trim()) return; setCourse({ ...course, externalAIFeedback: [...(course.externalAIFeedback ?? []), { id: uid(), task, response: feedback.trim(), provider: provider.trim() || undefined, createdAt: new Date().toISOString(), assignmentId: assignment?.id, sloIds: assignment?.linkedSloIds }] }); setFeedback(""); }}>Save feedback</button></details></details>;
}
