"use client";

import { useEffect, useState } from "react";
import { reviewSloStructure, suggestedSloRevision } from "@/src/lib/sloReview";
import type { CourseRecord, SLO } from "@/src/types/course";

export default function QuickTools({ course, onOpenWorkspace }: { course: CourseRecord; onOpenWorkspace: () => void }) {
  const [statement, setStatement] = useState(""); const [bloomLevel, setBloomLevel] = useState<SLO["bloomLevel"]>("analyze"); const [aiMessage, setAiMessage] = useState("");
  const [aiStatus, setAiStatus] = useState("Checking AI development state…");
  useEffect(() => { void fetch("/api/ai/status").then((response) => response.json()).then((data: { message?: string }) => setAiStatus(data.message ?? "AI development state is unavailable.")).catch(() => setAiStatus("AI development state is unavailable.")); }, []);
  const review = statement.trim() ? reviewSloStructure({ statement, bloomLevel }) : [];
  const askAi = async () => { setAiMessage("Reviewing with the server-side knowledge service…"); try { const response = await fetch("/api/ai/slo-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ statement, bloomLevel, courseContext: `${course.title} ${course.description}` }) }); const data = await response.json() as { summary?: string; suggestedRevision?: string; error?: string }; setAiMessage(data.error ?? `${data.summary}\n\nSuggested revision: ${data.suggestedRevision}`); } catch { setAiMessage("The AI review service is unavailable."); } };
  return <div><div className="section-header"><div className="eyebrow gold">Quick tools</div><h2>Work on one course-design decision</h2><p>These tools use the same course record and deterministic engines as Guided Course Design.</p></div><div className="status-panel warning" role="status"><strong>AI development state</strong><p>{aiStatus}</p></div><div className="tool-grid"><button className="tool-card" onClick={onOpenWorkspace}><strong>Find a learning activity</strong><span>Open the Activity Finder with this course’s context.</span></button><button className="tool-card" onClick={onOpenWorkspace}><strong>Check outcome–assessment alignment</strong><span>Open the dashboard’s linked course map.</span></button><button className="tool-card" onClick={onOpenWorkspace}><strong>Create or revise an assignment</strong><span>Use the TiLT assignment studio.</span></button></div><section className="dashboard-section"><h3>Review an SLO</h3><label className="field"><span className="field-label">Student learning outcome</span><textarea rows={3} value={statement} onChange={(event) => setStatement(event.target.value)} /></label><label className="field"><span className="field-label">Faculty-selected Bloom level</span><select value={bloomLevel} onChange={(event) => setBloomLevel(event.target.value as SLO["bloomLevel"])}>{(["remember", "understand", "apply", "analyze", "evaluate", "create"] as const).map((level) => <option key={level}>{level}</option>)}</select></label>{review.length > 0 && <><ul className="plain-list">{review.map((item) => <li key={item.dimension}><strong>{item.dimension.replaceAll("-", " ")}:</strong> {item.rationale}</li>)}</ul><p><strong>Editable suggested revision:</strong> {suggestedSloRevision(statement)}</p></>}<button className="ghost-button" disabled={!statement.trim()} onClick={askAi}>Ask the knowledge-grounded AI service</button>{aiMessage && <pre className="ai-response" aria-live="polite">{aiMessage}</pre>}</section></div>;
}
