"use client";

import { useEffect, useMemo, useState } from "react";
import { applySloReviewDecision } from "@/src/lib/sloReviewRecord";
import { reviewSloStructure } from "@/src/lib/sloReview";
import type { AiSloReviewRecord, CourseRecord, SLO } from "@/src/types/course";

const levels: SLO["bloomLevel"][] = ["remember", "understand", "apply", "analyze", "evaluate", "create"];
const uid = () => `slo-${Math.random().toString(36).slice(2, 9)}`;

function contextFor(course: CourseRecord) {
  return { title: course.title, discipline: course.discipline, level: course.level, modality: course.modality, description: course.description, goals: course.aspirationalGoals, materialExcerpts: course.materials.filter((material) => material.scope === "course" && material.status === "extracted" && material.extractedText.trim()).slice(0, 3).map((material) => ({ filename: material.filename, text: material.extractedText.slice(0, 4_000) })) };
}

export default function SloReviewStudio({ course, setCourse }: { course: CourseRecord; setCourse: (course: CourseRecord) => void }) {
  const [selectedId, setSelectedId] = useState(course.slos[0]?.id ?? "new");
  const selected = useMemo(() => course.slos.find((slo) => slo.id === selectedId), [course.slos, selectedId]);
  const [statement, setStatement] = useState(selected?.statement ?? "");
  const [bloomLevel, setBloomLevel] = useState<SLO["bloomLevel"]>(selected?.bloomLevel ?? "analyze");
  const [review, setReview] = useState<AiSloReviewRecord | null>(null); const [revision, setRevision] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const [usage, setUsage] = useState<{ availability?: { available: boolean; message: string }; estimate?: number | null; limits?: { today: number; todayLimit: number } } | null>(null);
  const [standardReview, setStandardReview] = useState<ReturnType<typeof reviewSloStructure> | null>(null);
  useEffect(() => { void fetch("/api/ai/usage").then((response) => response.json()).then(setUsage).catch(() => setUsage(null)); }, []);
  const choose = (id: string) => { setSelectedId(id); const slo = course.slos.find((item) => item.id === id); setStatement(slo?.statement ?? ""); setBloomLevel(slo?.bloomLevel ?? "analyze"); setReview(null); setRevision(""); setMessage(""); };
  const ask = async () => { if (!statement.trim() || !usage?.availability?.available) return; setLoading(true); setMessage(""); setReview(null); try { const response = await fetch("/api/ai/slo-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ statement, bloomLevel, courseContext: contextFor(course) }) }); const data = await response.json() as AiSloReviewRecord & { error?: string }; if (!response.ok || data.error) throw new Error(data.error ?? "AI review could not be completed."); setReview(data); setRevision(data.suggestedRevision); } catch (error) { setMessage(error instanceof Error ? error.message : "The AI review service is unavailable."); } finally { setLoading(false); } };
  const saveDecision = (decision: "accepted-revision" | "edited-revision" | "kept-original") => { if (!review) return; const slo = selected ?? { id: uid(), statement: review.originalSlo, bloomLevel, confirmed: false }; const finalStatement = decision === "kept-original" ? review.originalSlo : revision.trim(); if (!finalStatement) { setMessage("Enter an edited revision before saving it."); return; } const hasSlo = Boolean(selected); const next = hasSlo ? course : { ...course, slos: [...course.slos, slo] }; setCourse(applySloReviewDecision(next, slo, review, decision, finalStatement)); setSelectedId(slo.id); setStatement(finalStatement); setMessage(decision === "kept-original" ? "Kept the original SLO and recorded your decision." : "Saved your faculty decision and revision in this local course record."); };
  return <div><div className="section-header"><div className="eyebrow gold">SLO review</div><h2>Review a learning outcome with faculty judgment in control</h2><p>This optional prototype review uses only the relevant course context and extracted course materials. It does not send student-identifiable data or store the raw AI response.</p></div>
    <div className="form-grid two"><label className="field"><span className="field-label">Choose or create an SLO</span><select value={selectedId} onChange={(event) => choose(event.target.value)}><option value="new">Create a new SLO</option>{course.slos.map((slo) => <option key={slo.id} value={slo.id}>{slo.statement.slice(0, 100)}</option>)}</select></label><label className="field"><span className="field-label">Faculty-selected Bloom level</span><select value={bloomLevel} onChange={(event) => setBloomLevel(event.target.value as SLO["bloomLevel"])}>{levels.map((level) => <option key={level}>{level}</option>)}</select></label></div>
    <label className="field"><span className="field-label">Student learning outcome</span><textarea rows={4} maxLength={2000} value={statement} onChange={(event) => setStatement(event.target.value)} placeholder="Students will evaluate competing explanations using disciplinary evidence." /></label><section className="principle-strip"><div><strong>About AI-assisted features</strong><br />Most Course Guide tools do not use generative AI. AI is used only when you explicitly choose an AI-assisted action; standard course-design work does not generate AI charges.</div></section><div className="header-actions"><button className="secondary-button" disabled={!statement.trim()} onClick={() => { setStandardReview(reviewSloStructure({ statement, bloomLevel })); setMessage("Standard Review completed. No AI was used."); }}>Standard Review</button><button className="ghost-button" disabled={loading || !statement.trim() || !usage?.availability?.available} onClick={ask}>{loading ? "Reviewing…" : "AI-Assisted Review"}</button></div><p className="muted">{usage?.availability?.available ? `Uses the institution’s AI allowance. Estimated cost: ${(usage.estimate ?? null) === null ? "pricing not configured" : (usage.estimate ?? 0) < 0.01 ? "less than $0.01" : `about $${(usage.estimate ?? 0).toFixed(2)}`}. ${usage.limits ? `AI-assisted uses today: ${usage.limits.today} of ${usage.limits.todayLimit}.` : ""}` : (usage?.availability?.message ?? "Checking AI-assisted feature availability…")}</p>{standardReview && <section className="dashboard-section"><h3>Standard Review <span className="muted">No AI used</span></h3><ul className="plain-list">{standardReview.map((item) => <li key={item.dimension}><strong>{item.dimension.replaceAll("-", " ")}:</strong> {item.rationale}</li>)}</ul><p>Standard Review uses rule-based checks for student-centered language, observable action, likely Bloom-level wording, and basic inclusion considerations. It does not provide the contextual depth of AI-Assisted Review.</p></section>}{message && <p className="status-panel warning" role="status">{message}</p>}
    {review && <section className="dashboard-section"><h3>Structured review</h3><p>{review.overallSummary}</p><div className="table-wrap"><table><thead><tr><th>Dimension</th><th>Faculty consideration</th><th>Rationale</th></tr></thead><tbody>{review.dimensions.map((item) => <tr key={item.dimension}><td>{item.dimension.replaceAll("-", " ")}</td><td>{item.status.replaceAll("-", " ")}</td><td>{item.rationale}</td></tr>)}</tbody></table></div><p><strong>Likely cognitive level:</strong> {review.likelyCognitiveLevel.level} — {review.likelyCognitiveLevel.rationale}</p><p><strong>Vague or non-observable wording:</strong> {review.vagueOrNonobservableWording.length ? review.vagueOrNonobservableWording.join(", ") : "None identified."}</p><p><strong>Portability / transfer:</strong> {review.portabilityAndTransfer.status.replaceAll("-", " ")} — {review.portabilityAndTransfer.rationale}</p><p><strong>Course-context consideration:</strong> {review.courseContextConsideration}</p><p><strong>Strengths:</strong> {review.strengths.join("; ") || "None specified."}</p><p><strong>Considerations:</strong> {review.considerations.join("; ") || "None specified."}</p><label className="field"><span className="field-label">Editable suggested revision</span><textarea rows={4} value={revision} onChange={(event) => setRevision(event.target.value)} /></label><p>{review.revisionExplanation}</p><div className="header-actions"><button className="secondary-button" onClick={() => saveDecision("accepted-revision")}>Accept revision</button><button className="ghost-button" onClick={() => saveDecision("edited-revision")}>Save edited revision</button><button className="ghost-button" onClick={() => saveDecision("kept-original")}>Keep original</button></div><h4>Sources and assumptions</h4>{review.sources.length ? <ul className="plain-list">{review.sources.map((source) => <li key={`${source.fileId}-${source.filename}`}>{source.filename}{source.category ? ` (${source.category})` : ""}</li>)}</ul> : <p>No visible knowledge-source result was returned for this review.</p>}<ul className="plain-list">{review.assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul></section>}
  </div>;
}
